allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - envio-darwin-arm64@3.5.1
  - envio-darwin-x64@3.5.1
  - envio-linux-arm64@3.5.1
  - envio-linux-x64-musl@3.5.1
  - envio-linux-x64@3.5.1
  - envio@3.5.1
